const icon = (name, label = '') => `<svg class="rb-icon"${label ? ` role="img" aria-label="${label}"` : ' aria-hidden="true"'}><use href="src/icons.svg#${name}"></use></svg>`;
const stack = (content) => `<div class="preview-stack">${content}</div>`;

window.RAIF_COMPONENTS = [
  { group: 'Actions', id: 'button', name: 'Button', description: 'Triggers an action with primary, secondary, tertiary, danger, loading, and disabled emphasis.', preview: stack(`<button class="rb-button rb-button--primary">Open an account</button><button class="rb-button rb-button--secondary">Learn more</button><button class="rb-button rb-button--tertiary">Calculate ${icon('arrow-right')}</button><button class="rb-button rb-button--primary" disabled>Unavailable</button>`), accessibility: ['Use a button for actions and a link for navigation.', 'Keep labels short, unique, and action-oriented.', 'Use one primary action per page or task surface.'] },
  { group: 'Actions', id: 'icon-button', name: 'Icon button', description: 'Compact action for familiar operations such as search, close, edit, or delete.', preview: stack(`<button class="rb-icon-button" aria-label="Search">${icon('search')}</button><button class="rb-icon-button" aria-label="Edit">${icon('edit')}</button><button class="rb-icon-button" aria-label="Delete">${icon('trash')}</button>`), accessibility: ['Every icon-only button requires an accessible name.', 'Use familiar symbols and provide a tooltip when meaning may be unclear.'] },
  { group: 'Actions', id: 'link', name: 'Link', description: 'Navigates to another page, resource, or section.', preview: stack(`<a class="rb-link" href="#">View product details ${icon('arrow-right')}</a><a class="rb-link" href="#">Download conditions ${icon('download')}</a>`), accessibility: ['Describe the destination rather than using “click here”.', 'Use an external-link cue when navigation leaves the current service.'] },
  { group: 'Actions', id: 'toggle-group', name: 'Toggle group', description: 'Selects one view or mode from a short, visible set.', preview: stack(`<div class="rb-toggle-group" aria-label="Customer type"><button aria-pressed="true">Personal</button><button aria-pressed="false">Business</button><button aria-pressed="false">Corporate</button></div>`), accessibility: ['Expose selected state with aria-pressed.', 'Keep options mutually exclusive and concise.'] },
  { group: 'Actions', id: 'numeric-stepper', name: 'Numeric stepper', description: 'Adjusts a numeric value with direct entry and increment controls.', preview: stack(`<button class="rb-icon-button" aria-label="Decrease">${icon('minus')}</button><strong>3,000,000 HUF</strong><button class="rb-icon-button" aria-label="Increase">${icon('plus')}</button>`), accessibility: ['Name increment and decrement controls.', 'Do not rely on buttons alone; allow keyboard entry where appropriate.'] },

  { group: 'Forms', id: 'field', name: 'Field', description: 'Composes a label, description, control, and validation message.', preview: stack(`<label class="rb-field"><span class="rb-label">Monthly income <span class="rb-label__required">*</span></span><span class="rb-description">Enter your verified net income.</span><input class="rb-input" type="text" value="450,000"><span class="rb-description">HUF per month</span></label>`), accessibility: ['Associate every control with a visible label.', 'Keep help text before errors in the reading order.'] },
  { group: 'Forms', id: 'input', name: 'Input', description: 'Single-line text, email, number, amount, and formatted data entry.', preview: stack(`<label class="rb-field"><span class="rb-label">Full name</span><input class="rb-input" placeholder="Enter your name"></label><label class="rb-field"><span class="rb-label">Amount</span><span class="rb-input-group"><input class="rb-input" value="3,000,000"><span>HUF</span></span></label>`), accessibility: ['Use the correct input type and autocomplete value.', 'Do not use placeholder text as the only label.'] },
  { group: 'Forms', id: 'phone-input', name: 'Phone input', description: 'Phone number field with a visible country prefix.', preview: stack(`<label class="rb-field"><span class="rb-label">Phone number</span><span class="rb-input-group"><span>+36</span><input class="rb-input" type="tel" placeholder="__/___-____" autocomplete="tel-national"></span></label>`), accessibility: ['Use autocomplete="tel" or tel-national.', 'Keep formatting guidance available while typing.'] },
  { group: 'Forms', id: 'date-input', name: 'Date input', description: 'Date entry with a calendar affordance and format hint.', preview: stack(`<label class="rb-field"><span class="rb-label">Date observed</span><span class="rb-date-input"><input class="rb-input" placeholder="YYYY.MM.DD"><svg class="rb-icon" aria-hidden="true"><use href="src/icons.svg#calendar"></use></svg></span></label>`), accessibility: ['Communicate the expected format in text.', 'Calendar selection must remain keyboard accessible.'] },
  { group: 'Forms', id: 'select', name: 'Select', description: 'Chooses one value from a compact list.', preview: stack(`<label class="rb-field"><span class="rb-label">Issue type</span><select class="rb-select"><option>Select an option</option><option>Cards and payments</option><option>Loans</option><option>Digital banking</option></select></label>`), accessibility: ['Use a native select when advanced custom behaviour is unnecessary.', 'Start with a clear prompt option when selection is required.'] },
  { group: 'Forms', id: 'textarea', name: 'Textarea', description: 'Multi-line entry with an optional character counter.', preview: stack(`<label class="rb-field" style="width:100%"><span class="rb-label">Describe the issue</span><textarea class="rb-textarea" maxlength="2000"></textarea><span class="rb-description">2,000 characters remaining</span></label>`), accessibility: ['Do not prevent paste.', 'Announce character limits before they block entry.'] },
  { group: 'Forms', id: 'checkbox', name: 'Checkbox', description: 'Selects zero or more independent options.', preview: stack(`<label class="rb-checkbox"><input type="checkbox"><span class="rb-checkbox__control"></span><span>Receive product updates</span></label><label class="rb-checkbox"><input type="checkbox" checked><span class="rb-checkbox__control"></span><span>I accept the privacy notice</span></label>`), accessibility: ['Use a fieldset and legend for related checkboxes.', 'Place long legal labels after the control and keep links operable.'] },
  { group: 'Forms', id: 'radio', name: 'Radio', description: 'Selects one option from a mutually exclusive group.', preview: stack(`<fieldset style="border:0;padding:0"><legend class="rb-label">Verified monthly income</legend><label class="rb-radio"><input name="income" type="radio" checked><span class="rb-radio__control"></span><span>At least 450,000 HUF</span></label><label class="rb-radio"><input name="income" type="radio"><span class="rb-radio__control"></span><span>300,000–449,000 HUF</span></label></fieldset>`), accessibility: ['Group radios with fieldset and legend.', 'Arrow-key selection should follow native browser behaviour.'] },
  { group: 'Forms', id: 'switch', name: 'Switch', description: 'Turns an immediate setting on or off.', preview: stack(`<label class="rb-switch"><input type="checkbox" checked><span class="rb-switch__control"></span><span>Statistical cookies</span></label><label class="rb-switch"><input type="checkbox"><span class="rb-switch__control"></span><span>Functional cookies</span></label>`), accessibility: ['Use a checkbox when the action requires later submission.', 'State labels should describe the setting, not “on” or “off”.'] },
  { group: 'Forms', id: 'file-upload', name: 'File upload', description: 'Uploads one or more supporting documents.', preview: stack(`<label class="rb-file-upload"><strong>Upload supporting documents</strong><span class="rb-description">PDF, JPG or PNG · max 10 MB</span><input type="file" accept=".pdf,.jpg,.jpeg,.png"></label>`), accessibility: ['List accepted formats and limits before the input.', 'Announce upload progress and validation results.'] },
  { group: 'Forms', id: 'search', name: 'Search', description: 'Pairs a labelled search input with a submit action.', preview: stack(`<form class="rb-search" role="search"><input class="rb-input" type="search" aria-label="Search the site" placeholder="Search"><button class="rb-button rb-button--primary" aria-label="Submit search">${icon('search')}<span>Search</span></button></form>`), accessibility: ['Use role="search" on the form.', 'Provide a visible label or an accessible name.'] },
  { group: 'Forms', id: 'validation', name: 'Validation message', description: 'Explains how to correct an invalid field.', preview: stack(`<label class="rb-field"><span class="rb-label">Email address</span><input class="rb-input" aria-invalid="true" aria-describedby="email-error" value="anna@"><span id="email-error" class="rb-validation">Enter a complete email address.</span></label>`), accessibility: ['Connect the message with aria-describedby.', 'Explain the correction; do not only state that a value is invalid.'] },
  { group: 'Forms', id: 'error-summary', name: 'Error summary', description: 'Collects form errors at the top of a failed submission.', preview: stack(`<section class="rb-error-summary" aria-labelledby="error-title"><h3 id="error-title">There is a problem</h3><ul><li><a href="#">Enter your full name</a></li><li><a href="#">Select an issue type</a></li></ul></section>`), accessibility: ['Move focus to the summary after failed submission.', 'Each message should link to the relevant field.'] },

  { group: 'Feedback', id: 'alert', name: 'Alert', description: 'Communicates informational, success, warning, or error status.', preview: stack(`<div class="rb-alert rb-alert--info">${icon('info')}<div class="rb-alert__content"><strong>Planned maintenance</strong><span>Digital services may be unavailable from 23:00.</span></div></div><div class="rb-alert rb-alert--success">${icon('check')}<div class="rb-alert__content"><strong>Application saved</strong><span>You can continue later.</span></div></div>`), accessibility: ['Use role="status" for non-urgent updates and role="alert" for urgent errors.', 'Do not communicate severity by colour alone.'] },
  { group: 'Feedback', id: 'badge', name: 'Badge', description: 'Compact status or metadata label.', preview: stack(`<span class="rb-badge">In progress</span><span class="rb-badge rb-badge--success">Available</span><span class="rb-badge rb-badge--danger">Action required</span>`), accessibility: ['Keep badge text explicit.', 'Avoid using badges as the only interactive target.'] },
  { group: 'Feedback', id: 'chip', name: 'Chip', description: 'Highlights a small category, promotion, or applied filter.', preview: stack(`<span class="rb-chip">New</span><span class="rb-chip">Loans</span><span class="rb-chip">Mobile banking</span>`), accessibility: ['Do not encode critical information in a decorative chip alone.'] },
  { group: 'Feedback', id: 'tag', name: 'Tag', description: 'Represents a removable selection or category.', preview: stack(`<span class="rb-tag">Accounts <button aria-label="Remove Accounts">${icon('close')}</button></span><span class="rb-tag">Cards <button aria-label="Remove Cards">${icon('close')}</button></span>`), accessibility: ['Name the remove action with the tag value.', 'Keep the visible tag text separate from the button label.'] },
  { group: 'Feedback', id: 'spinner', name: 'Spinner', description: 'Indicates indeterminate loading for a short operation.', preview: stack(`<span class="rb-spinner" role="status" aria-label="Loading"></span><button class="rb-button rb-button--primary rb-button--loading" disabled><span class="rb-spinner"></span>Loading…</button>`), accessibility: ['Provide a text alternative such as Loading.', 'Use progress for operations with a known completion value.'] },
  { group: 'Feedback', id: 'progress', name: 'Progress', description: 'Shows known completion in a process.', preview: stack(`<div style="width:100%"><div class="rb-progress" role="progressbar" aria-valuenow="68" aria-valuemin="0" aria-valuemax="100"><span style="width:68%"></span></div><p class="rb-description">68% complete</p></div>`), accessibility: ['Expose min, max, and current values.', 'Include a textual state when progress is important.'] },
  { group: 'Feedback', id: 'skeleton', name: 'Skeleton', description: 'Reserves layout while content is loading.', preview: stack(`<div style="display:grid;gap:.75rem;width:100%"><div class="rb-skeleton" style="height:8rem"></div><div class="rb-skeleton" style="width:65%"></div><div class="rb-skeleton" style="width:90%"></div></div>`), accessibility: ['Hide purely visual skeleton shapes from assistive technology.', 'Announce the loading state on the containing region.'] },
  { group: 'Feedback', id: 'tooltip', name: 'Tooltip', description: 'Provides a short label or explanation on hover and focus.', preview: stack(`<span class="rb-tooltip-wrap"><button class="rb-icon-button" aria-describedby="tip-help">${icon('info')}</button><span id="tip-help" role="tooltip" class="rb-tooltip">The annual percentage rate includes fees.</span></span>`), accessibility: ['Show the tooltip on keyboard focus as well as hover.', 'Never place essential interactive content inside a tooltip.'] },
  { group: 'Feedback', id: 'popover', name: 'Popover', description: 'Displays contextual non-modal content near a trigger.', preview: stack(`<div class="rb-popover"><strong>Rate information</strong><p>The displayed APR is calculated from the selected amount and term.</p><a class="rb-link" href="#">Read conditions</a></div>`), accessibility: ['Move focus into interactive popovers when opened.', 'Support Escape and restore focus to the trigger.'] },
  { group: 'Feedback', id: 'dialog', name: 'Dialog', description: 'Interrupts the flow for a focused confirmation or task.', preview: stack(`<button class="rb-button rb-button--primary" data-demo-dialog>Open dialog</button><dialog class="rb-dialog"><h2>Continue application?</h2><p>Your current calculation will be saved.</p><div class="rb-dialog__actions"><button class="rb-button rb-button--secondary" data-dialog-close>Cancel</button><button class="rb-button rb-button--primary">Continue</button></div></dialog>`), accessibility: ['Use a clear heading and initial focus target.', 'Trap focus while open and restore it when closed.'] },
  { group: 'Feedback', id: 'toast', name: 'Toast', description: 'Confirms a lightweight action without blocking work.', preview: stack(`<div class="rb-alert rb-alert--success" role="status">${icon('check')}<div class="rb-alert__content"><strong>Copied</strong><span>The account number is on your clipboard.</span></div></div>`), accessibility: ['Use a polite live region for confirmations.', 'Do not use a toast for information that must be acknowledged.'] },

  { group: 'Content', id: 'card', name: 'Card', description: 'Groups product or editorial content into a single surface.', preview: stack(`<article class="rb-card rb-card--interactive" style="max-width:24rem"><div class="rb-card__media"></div><div class="rb-card__body"><span class="rb-card__category">Loans</span><h3>Personal loan</h3><p>Apply online and calculate your monthly payment.</p><strong>APR: 9.9%–19.6%</strong><a class="rb-button rb-button--primary" href="#">Calculate</a></div></article>`), accessibility: ['Use one clear interactive target for a fully clickable card.', 'Preserve semantic headings within card collections.'] },
  { group: 'Content', id: 'simple-card', name: 'Simple card', description: 'Compact task or destination card used in help-me-choose grids.', preview: stack(`<article class="rb-card rb-simple-card" style="width:min(100%,32rem)"><span class="rb-wordmark__mark">${icon('card')}</span><h3>Open a bank account</h3><button class="rb-icon-button" aria-label="Open a bank account">${icon('arrow-right')}</button></article>`), accessibility: ['Avoid multiple competing links inside the compact card.', 'Use a heading that describes the destination.'] },
  { group: 'Content', id: 'surface-banner', name: 'Surface banner', description: 'Wide promotional surface with message, art, and call to action.', preview: `<article class="rb-surface-banner" style="width:100%"><div><span class="rb-chip">Mobile banking</span><h2>Everyday banking in one app</h2><p>Manage accounts, cards, payments, and savings wherever you are.</p><button class="rb-button rb-button--primary">Learn more</button></div><div class="rb-surface-banner__art">R</div></article>`, accessibility: ['Keep decorative art out of the accessibility tree.', 'Ensure foreground contrast remains sufficient over imagery.'] },
  { group: 'Content', id: 'table', name: 'Table', description: 'Displays comparable financial or product data.', preview: `<div class="rb-table-wrap" style="width:100%"><table class="rb-table rb-table--striped"><thead><tr><th>Product</th><th>Interest</th><th>APR</th></tr></thead><tbody><tr><td>Personal loan</td><td>9.49%</td><td>9.9%</td></tr><tr><td>Credit card</td><td>—</td><td>35.1%–37.7%</td></tr></tbody></table></div>`, accessibility: ['Use table headers with correct scope.', 'Provide a caption when the surrounding context is not sufficient.'] },
  { group: 'Content', id: 'divider', name: 'Divider', description: 'Separates adjacent content groups without introducing hierarchy.', preview: stack(`<div style="width:100%"><p>Account information</p><hr class="rb-divider"><p>Contact information</p></div>`), accessibility: ['Use a heading when the separation conveys a new section.', 'Decorative dividers should not add unnecessary announcements.'] },

  { group: 'Navigation', id: 'breadcrumbs', name: 'Breadcrumbs', description: 'Shows the current page within the site hierarchy.', preview: stack(`<nav aria-label="Breadcrumb"><ol class="rb-breadcrumbs"><li><a class="rb-link" href="#">Home</a>${icon('chevron-right')}</li><li><a class="rb-link" href="#">Loans</a>${icon('chevron-right')}</li><li aria-current="page">Personal loan</li></ol></nav>`), accessibility: ['Wrap the trail in navigation labelled Breadcrumb.', 'Mark the current page with aria-current="page".'] },
  { group: 'Navigation', id: 'tabs', name: 'Tabs', description: 'Switches between related content views without page navigation.', preview: `<div class="rb-tabs" style="width:100%"><div class="rb-tabs__list" role="tablist"><button role="tab" aria-selected="true">Overview</button><button role="tab" aria-selected="false">Conditions</button><button role="tab" aria-selected="false">Documents</button></div><div class="rb-tabs__panel" role="tabpanel">Product overview content.</div></div>`, accessibility: ['Implement arrow-key movement within the tab list.', 'Associate each tab with its panel.'] },
  { group: 'Navigation', id: 'details', name: 'Details', description: 'Reveals supporting information on demand.', preview: `<div style="width:100%"><details class="rb-details" open><summary>What documents do I need? ${icon('plus')}</summary><div class="rb-details__content">Identity documents and proof of income may be required.</div></details><details class="rb-details"><summary>How long does it take? ${icon('plus')}</summary><div class="rb-details__content">Timing depends on verification and credit assessment.</div></details></div>`, accessibility: ['Prefer native details and summary for simple disclosure.', 'The summary must describe the hidden content.'] },
  { group: 'Navigation', id: 'pagination', name: 'Pagination', description: 'Moves through a long, ordered set of pages.', preview: stack(`<nav class="rb-pagination" aria-label="Pagination"><button aria-label="Previous page">${icon('arrow-left')}</button><button aria-current="page">1</button><button>2</button><button>3</button><button aria-label="Next page">${icon('arrow-right')}</button></nav>`), accessibility: ['Label previous and next controls.', 'Mark the current page with aria-current.'] },
  { group: 'Navigation', id: 'stepper', name: 'Process stepper', description: 'Shows progress through a multi-step banking flow.', preview: `<ol class="rb-stepper" style="--rb-steps:4;width:100%"><li class="is-complete"><span>${icon('check')}</span><b>Calculate</b></li><li aria-current="step"><span>2</span><b>Details</b></li><li><span>3</span><b>Review</b></li><li><span>4</span><b>Done</b></li></ol>`, accessibility: ['Use an ordered list.', 'Mark the active item with aria-current="step".'] },
  { group: 'Navigation', id: 'header', name: 'Header', description: 'Three-level banking navigation: service links, primary product navigation, and online-banking action.', preview: `<header class="rb-header" style="width:100%"><div class="rb-header__service"><b>PERSONAL</b><span>PREMIUM BANKING</span><span>BUSINESS</span><span>Search · Branches · EN</span></div><div class="rb-header__main"><a class="rb-wordmark" href="#"><span class="rb-wordmark__mark">╳</span><span>RAIFFEISEN BANK</span></a><nav class="rb-header__nav"><a href="#">Accounts</a><a href="#">Loans</a><a href="#">Savings</a><a href="#">Digital</a></nav><button class="rb-button rb-button--primary">Online banking</button></div></header>`, accessibility: ['Provide one clear site-home link.', 'Use separate labels for service and primary navigation.'] },
  { group: 'Navigation', id: 'footer', name: 'Footer', description: 'Multi-column destination map with regulatory and legal metadata.', preview: `<footer class="rb-footer" style="width:100%"><div class="rb-footer__group"><h3>Raiffeisen Bank</h3><a href="#">Contact</a><a href="#">Branches and ATMs</a></div><div class="rb-footer__group"><h3>Consumer protection</h3><a href="#">Complaints</a><a href="#">Privacy</a></div><div class="rb-footer__group"><h3>Information</h3><a href="#">Fees and conditions</a><a href="#">Exchange rates</a></div><div class="rb-footer__group"><h3>Products</h3><a href="#">Personal</a><a href="#">Business</a></div><p class="rb-footer__meta">© 2026 · Legal · Sitemap · Imprint</p></footer>`, accessibility: ['Use descriptive headings for link groups.', 'Avoid repeating links already available in the primary navigation unless useful.'] },

  { group: 'Foundations', id: 'icons', name: 'Icons', description: 'Dependency-free line icon sprite with 35 interface symbols and consistent 24×24 geometry.', preview: '', accessibility: ['Decorative icons must use aria-hidden="true".', 'Meaningful standalone icons require an accessible name.', 'Use one icon per button and prefer placement before text.'] },
  { group: 'Foundations', id: 'typography', name: 'Typography', description: 'Amalia-first type scale with safe Arial and Helvetica fallbacks.', preview: '', accessibility: ['Preserve heading order independently of visual size.', 'Do not use all caps for long labels or paragraphs.'] },
  { group: 'Foundations', id: 'tokens', name: 'Design tokens', description: 'Portable CSS custom properties for colour, shape, shadow, typography, and control sizing.', preview: '', accessibility: ['Validate colour combinations against WCAG contrast requirements.', 'Do not override focus-ring tokens with invisible styles.'] }
];

window.RAIF_ICONS = ['search','menu','close','check','chevron-down','chevron-right','arrow-right','arrow-left','plus','minus','info','warning','error','calendar','clock','location','phone','mail','user','users','lock','login','document','download','upload','edit','trash','chat','bank','card','home','globe','external','moon','copy'];
